apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m4c8zirjd-nodejs
  janus-idp.io/tekton: m4c8zirjd-nodejs
  backstage.io/kubernetes-id: m4c8zirjd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m4c8zirjd-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
